echo "Hello My name is Sandesh "
echo "I am learning AWS DevOps"
echo "I'm trying to create merge conflict"
echo "Hello, How are you?"
echo "Welcome to Young Minds"
echo "Hello batch-19, We are learning Develops"
echo "Hello Batch-20"
echo "AWS is completed now.."
