echo "My name is Sandesh"
echo "I have completed my Graduation"
echo "Ohhhhhhhh!!"
echo "Yessssssssss!!"
echo "Abhiiiiii""
echo "India ka tyohaaaar"
echo "Big billion sell"
echo "Hybrid DTSI"
echo "I dont like Talking more"
