echo"My name is Ram"
echo "I am learning full stack devlopment"
echo "I dont want any conflict"
echo "Hello, How are you?"
echo "Welcome to Young Minds"
echo "Hello batch-19, We are learning Develops"
echo "Hello Batch-20"
echo "AWS is completed now.."
